name: Parse Gradle File

on:
  workflow_dispatch:
    inputs:
      gradle_file:
        description: 'Content of the gradle file'
        required: true
        type: string
      blueprint:
        description: 'The blueprint of the entity'
        required: true
        type: string
      idenfifier:
        description: 'The identifier of the entity'
        required: true
        type: string
      run_id:
        description: 'The ID of the automation run'
        required: true
        type: string

jobs:
  parse-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Parse Gradle file and Update Port Entity
        env:
          PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
          PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
          GRADLE_FILE_CONTENT: ${{ github.event.inputs.gradle_file }}
          BLUEPRINT: ${{ github.event.inputs.blueprint }}
          IDENTIFIER: ${{ github.event.inputs.idenfifier }}
          RUN_ID: ${{ github.event.inputs.run_id }}
        run: |
          bun run src/index.ts

      - name: Report success
        if: success()
        run: echo "Successfully parsed Gradle file and updated Port entity"

      - name: Report failure
        if: failure()
        run: echo "Failed to parse Gradle file or update Port entity"